ecommerce-django-main/authapp/urls.py
from django.urls import path
from .views import edit, dashboard, logoutuser, register, registerUser, signIn
from django.urls import reverse_lazy
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetDoneView, PasswordResetView,
                                       PasswordResetCompleteView, PasswordResetConfirmView,
                                       PasswordChangeView, PasswordChangeDoneView,
                                       PasswordResetDoneView)

app_name = 'authapp'

urlpatterns = [
    path('register/', register, name='register'),
    path('registeruser/', registerUser, name='registeruser'),
    path('edit/', edit, name='edit'),
    path('dashboard/', dashboard, name='dashboard'),
    path('', signIn, name='login'),
    path('logout/', logoutuser, name='logout'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='authapp/password_change_form.html'), name='password_change'),
    path('password_change/dond/', PasswordChangeDoneView.as_view(template_name='authapp/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='authapp/password_reset_form.html',
        email_template_name='authapp/password_reset_email.html',
        success_url=reverse_lazy('authapp:password_reset_done')), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='authapp/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='authapp/password_reset_confirm.html',
        success_url=reverse_lazy('authapp:login')), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='authapp/password_reset_complete.html'), name='password_reset_complete'),

]

ecommerce-django-main/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produits.urls')),
    path('auth', include('authapp.urls')),
    path('', include('subcriptions.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)
   

ecommerce-django-main/produits/urls.py
from django.urls import path
from produits.views import *

app_name = 'produits'
urlpatterns = [
    path('', index, name='home'),
    path('statistique', statistique, name='statistique'),

    #Seller
    path('list', product_seller_list, name='produtListSeller'),
    path('addproduct',  addProduct, name=' addproduct'),
    path('modifier/<int:pk>', EditViewProduct.as_view(), name='produit_detail'),
    path('supprimer/<int:pk>', DeleteViewProduct.as_view(), name='supprimmer_produit'),

    # Clients
    path('detail/<int:myid>/', detail, name="product_detail"),
    path('add_single_to_card/<int:pk>/', add_single_to_card, name='add_single_to_card'),
    path('categories/<int:pk>/',  all_categories, name='categories'),
    path('add_to_card/<int:pk>/', add_to_card, name='add_to_card'),
    path('remove_single_item_from_cart/<int:pk>', remove_single_item_from_cart, name="remove_single_item_from_cart"),
    path('remove_from_card/<int:pk>/', remove_from_card, name='remove_from_card'),
    path('checkout/<int:id>', checkout, name='checkout'),
    path('confirmation', confimation, name='confirmation'),
    path('order-summary', OrderSummary.as_view(), name="order-summary"),

    #Admin
    path('allproduct', product_sellers_list, name='allproducts'),
    path('profile', profile, name='profile'),
    path('modif/<int:pk>', UserEditView.as_view(), name='user_detail'),

    

]

ecommerce-django-main/produits/models.py
from tkinter import CASCADE
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _ 
from authapp.models import  UserRegistrationModel
# Create your models here.

class Categorie(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = _("Categorie")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.name
class Produit(models.Model):
    user = models.ForeignKey(UserRegistrationModel, on_delete=models.CASCADE)
    name = models.CharField(_("Nom du produit"), max_length=50)
    categorie = models.ForeignKey(Categorie, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products', null=True, blank=True)
    description = models.TextField(_("Description du produit"))
    prix = models.PositiveIntegerField(_("Prix du produit"))
    date_added = models.DateTimeField(auto_now_add=True)
    mode_payement = models.CharField(_('Mode De Payement'), max_length=100, default="Orange Money")
    
    class Meta:
        verbose_name = _("Produit")
        verbose_name_plural = _("Produits")
        ordering = ['-date_added']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("produits:produit_detail", kwargs={"pk": self.pk})

    def get_add_to_card_url(self):
        return reverse("produits:add_to_card", kwargs={"pk": self.pk})

    def get_remove_from_card_url(self):
        return reverse("produits:remove_from_card", kwargs={"pk": self.pk})    
         
    


class OrderItem(models.Model):
    item = models.ForeignKey(Produit, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    user = models.ForeignKey(UserRegistrationModel, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)


    def __str__(self):
        return f"{self.quantity} de {self.item}"

    def get_total_item_price(self):
        return self.quantity * self.item.prix   

       

class Order(models.Model):
    user = models.ForeignKey(UserRegistrationModel, on_delete=models.CASCADE)
    item = models.ManyToManyField(OrderItem, related_name='order')
    started_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    frais_de_livraison = models.IntegerField(_('Frais De Livraison'), default=500)
   
    class Meta:
        verbose_name = _("Order")
        verbose_name_plural = _("Orders")

    def __str__(self):
        return f"{self.user}-{self.started_date}"

    def get_absolute_url(self):
        return reverse("produits:order_detail", kwargs={"pk": self.pk})

    def get_frais(self):
        return self.frais_de_livraison    

    def get_total(self):
        total = 0
        for order_item in self.item.all():
            total += order_item.get_total_item_price()
        total += self.frais_de_livraison     
        return total    
         
    



   

ecommerce-django-main/produits/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView, ListView, View
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from produits.models import  Categorie, Order, OrderItem, Produit
from authapp.models import UserRegistrationModel
from .form import AddPrductForm, UserPrductForm
from django.contrib import messages
from django.core.paginator import Paginator
from django.utils import timezone


# Create your views here.
#home
def index(request):
    product_object = Produit.objects.all()
    categories = Categorie.objects.all()
    item_name = request.GET.get('item')
    if item_name !='' and item_name is not None:
        product_object = Produit.objects.filter(name__icontains=item_name)
    paginator = Paginator(product_object, 6)
    page = request.GET.get('page')
    product_object = paginator.get_page(page)
    return render(request, 'produits/index.html', {'produits': product_object, 'categories':categories})

#detail
def detail(request, myid):
    product_object = Produit.objects.get(id=myid)
    return render(request, 'produits/detail.html', {'product': product_object})    

def checkout(request):
    return render(request, 'produits/checkout.html')

login_required
def confimation(request):
    has_order=False
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        order.ordered=True
        order.save()
        has_order = True

    return render(request, 'produits/confirmation.html', {'has_order': has_order})            

#statistique des achats
@staff_member_required
def statistique(request):
    commande = Order.objects.all().order_by('-ordered_date')
    valide = Order.objects.all().count()
    order_item = OrderItem.objects.all().count()
    total = UserRegistrationModel.objects.all().count()
    return render(request, 'statistique/index.html', {'commande':commande, 'valid': valide, 'order_item':order_item, 'total': total})

@staff_member_required
def product_sellers_list(request):
    userproduits = Produit.objects.all()
    return render(request, 'statistique/table-export.html', {'userproduit':userproduits})    


@staff_member_required
def profile(request):
    userprofiles = UserRegistrationModel.objects.all()
    return render(request, 'statistique/app-profile.html', {'userprofiles':userprofiles})


class UserEditView(LoginRequiredMixin,UpdateView):
	model = UserRegistrationModel
	form_class = UserPrductForm
	template_name = 'statistique/profile_modification.html'
	success_url = reverse_lazy('produits:profile')


# seller
@login_required 
def product_seller_list(request):
    userproduit = Produit.objects.filter(user=request.user)
    return render(request, 'seller/tables.html', {'userproduit':userproduit})
        

@login_required
def addProduct(request):
    if request.method == 'POST':
        form = AddPrductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.user = request.user
            product.save()
            messages.success(request, "The product has been added successfully.")
            return redirect('/list')
        else:
            form = AddPrductForm(request.POST, request.FILES)
    else:
        form = AddPrductForm()
    return render(request, 'produits/add.html', {'form': form})

class EditViewProduct(LoginRequiredMixin,UpdateView):
	model = Produit
	form_class = AddPrductForm
	template_name = 'produits/edit_product.html'
	success_url = reverse_lazy('produits:produtListSeller')
	success_message = 'Le produit a ete bien modifie'




class DeleteViewProduct(LoginRequiredMixin,DeleteView):
	model = Produit
	template_name = 'produits/delete_product.html'
	success_url = reverse_lazy('produits:produtListSeller')
	success_message = 'le produit a été supprimé avec succès'    

class OrderSummary(LoginRequiredMixin ,View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object':order
            }
        except ObjectDoesNotExist:
            messages.error(self.request, "Vous n'avez mis aucun produit dans le panier")    
        return render(self.request, 'produits/checkout.html', context)


def all_categories(request, pk):
    categories = Categorie.objects.get(id=pk)
    produits = Produit.objects.filter(categorie=categories)
    context = {
        'produits':produits
    }
    return render(request, 'produits/index.html', context)
    
@login_required
def add_to_card(request, pk):
    item = get_object_or_404(Produit, id=pk)
    order_item, created = OrderItem.objects.get_or_create(item=item, user=request.user, ordered=False)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.item.filter(item__id=item.id).exists():
            order_item.quantity +=1
            order_item.save()
            messages.info(request, f"{item}-quantité augmenté")    
        else:
            order.item.add(order_item)
            messages.success(request, f"produit {item} ajouté")    
    else:
        ordered_date  = timezone.now()
        order = Order.objects.create(user=request.user, ordered_date=ordered_date)
        order.item.add(order_item)
        messages.info(request, f"produit {item} ajouté")
    return redirect('produits:product_detail', myid=pk)            

@login_required
def add_single_to_card(request, pk):
    item = get_object_or_404(Produit, id=pk)
    order_item, created = OrderItem.objects.get_or_create(item=item, user=request.user, ordered=False)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.item.filter(item__id=item.id).exists():
            order_item.quantity +=1
            order_item.save()
            messages.info(request, f"{item}-quantité augmenté")  
            return redirect("produits:order-summary")  
        else:
            order.item.add(order_item)
            messages.success(request, f"produit {item} ajouté")    
    else:
        ordered_date  = timezone.now()
        order = Order.objects.create(user=request.user, ordered_date=ordered_date)
        order.item.add(order_item)
        messages.info(request, f"produit {item} ajouté")
    return redirect("produits:product", id=pk)      

@login_required
def remove_single_item_from_cart(request, pk):
    item = get_object_or_404(Produit, id=pk)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.item.filter(item__id=item.pk).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.item.remove(order_item)
            messages.info(request, "La quantité de cet article a été mise à jour.")
            return redirect("produits:order-summary")
        else:
            messages.info(request, "Cet article n'était pas dans votre panier")
            return redirect("produit:product", id=pk)
    else:
        messages.info(request, "Vous n'avez pas de commande active")
        return redirect("produits:product", id=pk)


def remove_from_card(request, pk):
    item = get_object_or_404(Produit, id=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.item.filter(item__id=item.id).exists():
            order_item = OrderItem.objects.filter(item=item, user=request.user, ordered=False)[0]
            if order_item:
                order.item.remove(order_item)
                messages.info(request, f"produit {item} retiré")
                return redirect('produits:product_detail', myid=pk)
        else:
            messages.warning(request, f"Vous n'avez pas le produit {item} dans le parnier")
            return redirect('produits:product_detail', myid=pk)         
    else:
        messages.warning(request, f"Vous n'avez pas le produit {item} dans le parnier")
        return redirect('produits:product_detail', myid=pk) 

ecommerce-django-main/templates/produits/bases.html
{% load cart_template_tags %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">PHENIX-ACCUEIL</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    
  <ul class="navbar-nav nav-flex-icons text-danger">
    {% if request.user.is_authenticated %}
    <li class="nav-item">
      <a href="{% url 'produits:order-summary' %}" class="nav-link waves-effect">
        <span class="badge red z-depth-1 mr-1 text-danger"> {{ request.user|cart_item_count }} </span>
        <i class="fas fa-shopping-cart"></i>
        <span class="clearfix d-none d-sm-inline-block"> Panier </span>
      </a>
    </li>
    
    <li class="nav-item">
      <a class="nav-link waves-effect" href="{% url 'authapp:logout' %}">
        <span class="clearfix d-none d-sm-inline-block"> Se déconnecter </span>
      </a>
    </li>
    <li class="nav-item">
      <span class="clearfix d-none d-sm-inline-block"><i class="fa fa-user" aria-hidden="true"></i> {{request.user}} </span>
    </li>
    {% else %}
    <li class="nav-item">
      <a class="nav-link waves-effect" href="{% url 'authapp:login' %}">
        <span class="clearfix d-none d-sm-inline-block"> Connecter </span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link waves-effect" href="{% url 'authapp:registeruser'  %}">
        <span class="clearfix d-none d-sm-inline-block"> Creer un compte </span>
      </a>
    </li>
    {% endif %}
  </ul>
    
</nav>

ecommerce-django-main/templates/produits/checkout.html
{% extends "produits/base.html" %}

{% block content %}
{% include 'produits/bases.html' %}
<br>
<br>

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-2" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
</div>
{% endfor %}
{% endif %}
  <main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Récapitulatif de la commande</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Titre de l'article</th>
            <th scope="col">Prix</th>
            <th scope="col">Quantité</th>
            <th scope="col">Prix ​​total de l'article</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.item.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.name }}</td>
            <td>{{ order_item.item.prix }}</td>
            <td>
                <a href="{% url 'produits:remove_single_item_from_cart' order_item.item.id %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'produits:add_single_to_card' order_item.item.id %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
               {{ order_item.get_total_item_price }} FCFA
            
            <a style='color: red;' href="{% url 'produits:remove_from_card' order_item.item.id %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Votre panier est vide</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='/'>Continuer vos achats</a>
            </td>
        </tr>
        {% endfor %}
       
        <tr>
            <td colspan="4"><b>Frais De Livraison</b></td>
            <td><b>+{{ object.get_frais}} FCFA</b></td>
        </tr>
    
        {% if object.get_total %}
        <tr>
            <td colspan="4"><b>Total de la commande</b></td>
            <td><b>{{ object.get_total }} FCFA</b></td>
           
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='{% url 'produits:confirmation' %}'>Passer la commande</a>
            <a class='btn btn-primary float-right' href='/'>Continuer vos achats</a>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
  </main>

{% endblock content %}

ecommerce-django-main/templates/produits/index.html
{% extends 'produits/base.html' %}
{% load static %}
{% block content %}

<!-- banner bg main start -->
<div class="banner_bg_main">
   <!-- header top section start -->
   <div class="container">
      <div class="header_section_top">
         <div class="row">
            <div class="col-sm-12">
               <div class="custom_menu">
                  <ul>
                     <li><a href="#">Meilleures ventes</a></li>
                     <li><a href="#">Idées de cadeau</a></li>
                     <li><a href="#">Dernier</a></li>
                     <li><a href="#">Vendeurs</a></li>
                     <li><a href="#">Service Clients</a></li>

                  </ul>
               </div>
            </div>
         </div>
      </div>
   </div>
   <!-- header top section start -->
   <!-- logo section start -->
   <div class="logo_section">
      <div class="container">
         <div class="row">
            <div class="col-sm-12">
               <div class="logo"><a href="/"><img src="{% static 'ecom/images/logo.png' %}" alt="PHENIX"></a></div>
            </div>
         </div>
      </div>
   </div>
   <!-- logo section end -->
   <!-- header section start -->
   <div class="header_section">
      <div class="container">
         <div class="containt_main">
            <div id="mySidenav" class="sidenav">
               <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
               <a href="">Accueil</a>
               <a href="">Fashion</a>


               {% if user.is_authenticated and user.peut_vendre %}
               <a href="{% url 'authapp:dashboard' %}"> Votre Pannel<a />
                  {% else %}
                  <a href="{% url 'authapp:register' %}">Deviens vendeur</a>
                  <a href="{% url 'authapp:login' %}">Se connecter</a>
                  {% endif %}

            </div>
            <span class="toggle_icon" onclick="openNav()"><img src="{% static 'ecom/images/toggle-icon.png' %}"></span>
            <div class="dropdown">
               <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories
               </button>
               <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  {% for cat in categories  %}
                  <a class="dropdown-item" href="categories/{{cat.id}}/">{{ cat.name }}</a>
                  {% endfor %}

               </div>
            </div>
            <div class="main">
               <!-- Another variation with a button -->
               <form action="">
               <div class="input-group">
                 <input type="text" name="item" class="form-control" placeholder="Entrez le nom ...">
                  <div class="input-group-append">
                     <button class="btn btn-secondary" type="submit"
                        style="background-color: #f26522; border-color:#f26522 ">
                        <i class="fa fa-search"></i>
                     </button>
                  </div>
               </div>
            </form>
            </div>
            <div class="header_box">
               <div class="lang_box ">
                  <a href="#" title="Language" class="nav-link" data-toggle="dropdown" aria-expanded="true">
                     <img src="{% static 'ecom/images/flag-france.png' %}" class="mr-1" alt="flag">
                     Francais
                  </a>
                  <div class="dropdown-menu ">
                     <a href="#" class="dropdown-item">

                        <img src="{% static 'ecom/images/flag-uk.png'%}" alt="flag" class="mr-1 "
                           title="United Kingdom"> Anglais <i class="fa fa-angle-down ml-2" aria-hidden="true"></i>
                     </a>
                  </div>
               </div>
               <div class="login_menu">
                  <ul>
                     <li>
                        <div class="dropdown">
                           <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Deviens Vendeur
                           </button>
                           <div class="dropdown-menu login_menu_compte" aria-labelledby="dropdownMenuButton">

                              {% if user.is_authenticated and user.peut_vendre %}
                              <a class="dropdown-item" href="/authdashboard/"> Votre Pannel<a />
                                 {% else %}
                                 <a class="dropdown-item" href="{% url 'authapp:register' %}">Creer un compte</a>
                                 <a class="dropdown-item" href="{% url 'authapp:login' %}">Se connecter </a>
                                 {% endif %}
                           </div>
                        </div>
                     </li>
                     <li><a href="#">
                           <i class="fa fa-user" aria-hidden="true"></i>
                           <span class="padding_10">Panier</span></a>
                     </li>
                  </ul>
               </div>
            </div>
         </div>
      </div>
   </div>
   <!-- header section end -->
   <!-- banner section start -->
   <div class="banner_section layout_padding">
      <div class="container">
         <div id="my_slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
               <div class="carousel-item active">
                  <div class="row">
                     <div class="col-sm-12">
                        <h1 class="banner_taital">IMPOSEZ VOTRE STYLE</h1>
                        <div class="buynow_bt"><a href="/authregister/">Devenez vendeur</a></div>
                     </div>
                  </div>
               </div>
               <div class="carousel-item">
                  <div class="row">
                     <div class="col-sm-12">
                        <h1 class="banner_taital">IMPOSEZ VOTRE STYLE</h1>
                        <div class="buynow_bt"><a href="#">Devenez vendeur</a></div>
                     </div>
                  </div>
               </div>
               <div class="carousel-item">
                  <div class="row">
                     <div class="col-sm-12">
                        <h1 class="banner_taital">Deviens Vendeur <br>Avoir votre boutique en ligne</h1>
                        <div class="buynow_bt"><a href="/authregister/">Devenez vendeur</a></div>
                     </div>
                  </div>
               </div>
            </div>
            <a class="carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
               <i class="fa fa-angle-left"></i>
            </a>
            <a class="carousel-control-next" href="#my_slider" role="button" data-slide="next">
               <i class="fa fa-angle-right"></i>
            </a>
         </div>
      </div>
   </div>
   <!-- banner section end -->
</div>
<!-- banner bg main end -->
<!-- fashion section start -->
<div class="fashion_section">
   <div id="main_slider" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
         <div class="carousel-item active">
            <div class="container">
               <h1 class="fashion_taital">Tous Models</h1>
               <div class="fashion_section_2">
                  <div class="row">
                     {% for produit in produits %}
                     <div class="col-lg-4 col-sm-4">
                        <div class="box_main">
                           <h4 class="shirt_text">{{produit.name}}</h4>
                           <p class="price_text">FCFA <span style="color: #262626;"> {{ produit.prix }}</span></p>
                           <div class="tshirt_img"><img src="{{ produit.image.url }}"></div>
                           <div class="btn_main">
                              <div class="buy_bt">
                                 {% if user.is_authenticated  %}
                                 <a class="btn" style="color: #2A35BC;" href="detail/{{ produit.id }}">Acheter</a>
                                {% else %}
                                <button type="button" class="btn" style="color: #2A35BC;" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                                Acheter
                               </button>
                                {% endif %}
                                
                              </div>
                              <div class="seemore_bt"><a href="detail/{{ produit.id }}">Detail</a></div>
                           </div>
                        </div>
                     </div>
                     {% endfor %}
                  </div>
               </div>
            </div>
         </div>

      </div>
      <!-- pagination -->
      <div class="pagination">
         <span class="step-links">
            {% if produits.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ produits.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
               Page {{ produits.number }} of {{ produits.paginator.num_pages }}.
            </span>

            {% if produits.has_next %}
            <a href="?page={{ produits.next_page_number }}">next</a>
            <a href="?page={{ produits.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
         </span>
      </div>

      <!-- end pagination -->

      <div class="row mt-3">
         <div class="col-md-3 offset-md-4">
            <ul class="pagination">
               {% if produits.has_previous %}
               <li class="page-item">
                  <a class="page-link" href="?page={{ produits.previous_page_number }}">Precedent</a>
               </li>
               {% endif %}

               <li class="page-item active">
                  <a class="page-link" href="?page={{ produits.number }}">{{ produits.number }}</a>
               </li>

               {% if produits.has_next %}
               <li class="page-item">
                  <a class="page-link" href="?page={{ produits.next_page_number }}">Suivant</a>
               </li>
               {% endif %}

            </ul>
         </div>
      </div>

   </div>
</div>
<!-- fashion section end -->

<!-- Button trigger modal -->

 <!-- Modal -->
 <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
   <div class="modal-dialog">
     <div class="modal-content">
       <div class="modal-header">
         <h5 class="modal-title" id="staticBackdropLabel"> Connecter vous ou creer un compte </h5>
         <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
       </div>
       <div class="modal-body">
         <p class="lead text-xs-center">Il ne faut que quelques secondes pour le faire</p>
         <div class="lead text-xs-center"><a class="btn btn-info" href="{% url 'authapp:registeruser' %}">Créer un compte</a> ou
             <a class="btn btn-success" href="{% url 'authapp:login' %}">Connexion</a></div>
       </div>
       <div class="modal-footer">
         
       </div>
     </div>
   </div>
 </div>
 


{% endblock content %}