ecommerce-django-main/authapp/urls.py
from django.urls import path
from .views import edit, dashboard, logoutuser, register, registerUser, signIn
from django.urls import reverse_lazy
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetDoneView, PasswordResetView,
                                       PasswordResetCompleteView, PasswordResetConfirmView,
                                       PasswordChangeView, PasswordChangeDoneView,
                                       PasswordResetDoneView)

app_name = 'authapp'

urlpatterns = [
    path('register/', register, name='register'),
    path('registeruser/', registerUser, name='registeruser'),
    path('edit/', edit, name='edit'),
    path('dashboard/', dashboard, name='dashboard'),
    path('', signIn, name='login'),
    path('logout/', logoutuser, name='logout'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='authapp/password_change_form.html'), name='password_change'),
    path('password_change/dond/', PasswordChangeDoneView.as_view(template_name='authapp/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='authapp/password_reset_form.html',
        email_template_name='authapp/password_reset_email.html',
        success_url=reverse_lazy('authapp:password_reset_done')), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='authapp/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='authapp/password_reset_confirm.html',
        success_url=reverse_lazy('authapp:login')), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='authapp/password_reset_complete.html'), name='password_reset_complete'),

]

ecommerce-django-main/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produits.urls')),
    path('auth', include('authapp.urls')),
    path('', include('subcriptions.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)
   

ecommerce-django-main/authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser , User
from django.utils.translation import gettext_lazy as _
# Create your models here.


class UserRegistrationModel(AbstractUser):
    region = models.CharField(_('region'),max_length=100)
    ville = models.CharField(_('ville'), max_length=100)
    numero_telephone = models.CharField(_("numero whatsapp"), max_length=15)
    biographie = models.TextField()
    peut_vendre = models.BooleanField(default=False)
    ne_peut_vendre = models.BooleanField(_('Je veux vendre'), default=False)
    
   
    
    

ecommerce-django-main/authapp/forms.py
from .models import UserRegistrationModel
from django import forms
# from .models import Profile
from .models import UserRegistrationModel
from django.contrib.auth.forms import PasswordResetForm

 
class UserRegistration(forms.ModelForm):
    password1 = forms.CharField(label='Mot de passe', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repeter le Mot de password', widget=forms.PasswordInput)
    ne_peut_vendre = forms.BooleanField(label='JE VEUX VENDRE' ,required=True)
    class Meta:
        model = UserRegistrationModel
        fields = ('username', 'first_name', 'last_name', 'email', 'region', 'ville', 'numero_telephone', 'ne_peut_vendre', 'biographie')

        def clean_password2(self):
            password1 = self.cleaned_data.get('password1')
            password2 = self.cleaned_data.get('password2')

            if password1 and password2 and password1 != password2:
                raise forms.ValidationError('Les mots mots de passes sont different!!')
            return password2
        def clean_ne_peut_vendre(self):
            ne_peut_vendre = self.clean_data.get('ne_peux_vendre')
            if ne_peut_vendre:
                return ne_peut_vendre
            else:
                forms.ValidationError("vous devez cocher la case * JE VEUX VENDRE* ")                

    def save(self, commit=True):
        user = super(UserRegistration, self).save(commit=False)
        user.set_password(self.cleaned_data['password2'])
        if commit:
            user.save()
        return user


class UserEditForm(forms.ModelForm):
    class Meta:
        model = UserRegistrationModel
        fields = ('first_name', 'last_name', 'email', 'region', 'ville', 'numero_telephone', 'biographie')


class UserCustomerForm(forms.ModelForm):
    password1 = forms.CharField(label='Mot de passe', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repeter le Mot de password', widget=forms.PasswordInput)

    class Meta:
        model = UserRegistrationModel
        fields = ('username', 'first_name', 'last_name', 'email', 'region', 'ville', 'numero_telephone')

        def clean_password2(self):
            password1 = self.cleaned_data.get('password1')
            password2 = self.cleaned_data.get('password2')

            if password1 and password2 and password1 != password2:
                raise forms.ValidationError('Les mots mots de passes sont different!!')
            return password2

    def save(self, commit=True):
        user = super(UserCustomerForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password2'])
        if commit:
            user.save()
        return user

ecommerce-django-main/authapp/views.py
from django.http import request
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required

from produits.models import  Order
from .forms import UserCustomerForm, UserRegistration, UserEditForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required


# Create your views here.
#dashbord du vendeur
@login_required(login_url='/login')
def dashboard(request):
    order_list = []
    order = Order.objects.all()
    for order in order:
        for element in order.item.all():
            if element.item.user==request.user:
                order_list.append(element)           
    count =len(order_list)            
  

    context = {
        'count':count,
        'order_list':order_list,
        
        "welcome": "Welcome to your dashboard"
    }

    return render(request, 'seller/index.html', context=context)


def register(request):
    if request.method == 'POST':
        form = UserRegistration(request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(request, "Votre compte a été créé avec succès.")
            return render(request, 'authapp/register_done.html')
    else:
        form = UserRegistration()

    context = {
        "form": form
    }

    return render(request, 'authapp/register.html', context=context)

def registerUser(request):
    if request.method == 'POST':
        form = UserCustomerForm(request.POST or None)
        if form.is_valid():
            form.save()
            return redirect('/auth')
    else:
        form = UserCustomerForm()

    context = {
        "form": form
    }

    return render(request, 'authapp/registeruser.html', context=context)    

def signIn(request):
    error = False
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None and user.is_active:
            login(request, user)
            if user.peut_vendre:
                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))    
                return redirect('/')
            elif user.ne_peut_vendre:
                return render(request, 'authapp/peux_pas_vendre.html')
            else:
                return redirect('/')       
        else:
            error=True
    return render(request, 'registration/log.html',{'error':error})

@login_required
def logoutuser(request):
    logout(request)
    return redirect('/auth')    

@login_required(login_url='/login')
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        if user_form.is_valid():
            user_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
    context = {
        'form': user_form,
    }
    return render(request, 'authapp/edit.html', context=context)

ecommerce-django-main/templates/authapp/dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock title %}
{% block content %}
<h1>{{welcome}}</h1>
<br>
<a href="{% url 'authapp:edit' %}" class="btn btn-primary">Modifiez votre profile</a> --
<a href="{% url 'authapp:password_change' %}" class="btn btn-warning">Changez votre mot de passe</a>
<hr>
{% endblock content %}

ecommerce-django-main/templates/authapp/edit.html
{% extends "base.html" %} {% load bootstrap4 %} {% block title %}Edit {%endblock title %}
 {% block content %} 
 {% if form.errors %} 
 {% endif %}
<body class="bg-gradient-primary form">
  <div class="container">
    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-12">
            <div class="p-5">
              
              <div style="text-align: center">
                <h1>Modification</h1>
                <p>
                  veillez modifier vos informations.
                </p>
              </div>

              <form action="" method="post" class="form containe user">
                {% csrf_token %}
                 {% bootstrap_form form %} 
                <button
                  type="submit"
                  class="btn btn-warning btn-user btn-block"
                >
                  Modifier
                </button>
                <hr />

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
{% endblock content %}

ecommerce-django-main/templates/authapp/logged_out.html
{% extends "base.html" %}
{% block title %}Déconnecté{% endblock %}
{% block content %}
<h1>Déconnecté</h1>
<p>
    Vous avez été déconnecté avec succès.
    <hr>
    You can <a href="{% url 'authapp:login' %}">Reconnectez-vous</a>.
</p>
{% endblock %}

ecommerce-django-main/templates/authapp/password_change_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<h2>Changez votre mot de passe</h2>
<p>Utilisez le formulaire ci-dessous pour changer votre mot de passe</p>
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Envoyez</button>
    {% endbuttons %}
</form>
{% endblock content %}

ecommerce-django-main/templates/authapp/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Réinitialisation du mot de passe{% endblock %}
{% block content %}
<h2>Réinitialisation du mot de passe</h2>
<p>Votre mot de passe a été Réinitialisé. vous pouvez vouz
    <a href="{% url 'authapp:login' %}">Connecter maintenant</a></p>
{% endblock %}

ecommerce-django-main/templates/authapp/password_reset_confirm.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}réinitialisez votre mot de passe{% endblock %}
{% block content %}
<h1>Réinitialisez votre mot de passe</h1>
{% if validlink %}
<p>Veuillez entrer votre nouveau mot de passe deux fois :</p>
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary" value="Change my password">Envoyez</button>
    {% endbuttons %}
</form>
{% else %}
<p>Le lien de réinitialisation du mot de passe n'était pas valide, peut-être parce qu'il a
    déjà été utilisé. Veuillez demander une nouvelle réinitialisation de mot de passe.</p>
{% endif %}
{% endblock %}

ecommerce-django-main/templates/authapp/password_reset_done.html
{% extends "base.html" %}
{% block title %}Réinitialiser votre mot de passe{% endblock %}
{% block content %}
<h1>Réinitialiser votre mot de passe</h1>
<p>Nous vous avons envoyé par e-mail des instructions pour définir votre mot de passe.</p>
<p>Si vous ne recevez pas d'e-mail, assurez-vous d'avoir saisi
    l'adresse avec laquelle vous vous êtes inscrit.</p>
{% endblock %}

ecommerce-django-main/templates/authapp/password_reset_email.html
Quelqu'un a demandé la réinitialisation du mot de passe pour l'e-mail {{email}}. Suivez le lien ci-dessous
{{ protocol }}://{{ domain }}{% url "authapp:password_reset_confirm"
uidb64=uid token=token %}

ecommerce-django-main/templates/authapp/password_reset_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}réinitialisez votre mot de passe

{% endblock title %}
{% block content %}
<div class="container">
    <h2>Mot de passe oublié</h2>
    <p>Entrez votre adresse e-mail pour obtenir un nouveau mot de passe</p>
    <form action="" method="post" class="form ">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary" value="send e-mail">Envoyez</button>
        {% endbuttons %}
    </form>
</div>
{% endblock content %}

ecommerce-django-main/templates/authapp/peux_pas_vendre.html
{% extends "base.html" %}
{% block content %}
<h1>Bienvenue {{ request.user.username }}!</h1>
<p>Vous avez bien un compte mais qui n'est pas encore active Veillez patienter cela prendre 2 jours maximun.</p>
{% endblock content %}

ecommerce-django-main/templates/authapp/register.html
{% extends "base.html" %} {% load bootstrap4 %} {% block title %}Registration {%endblock title %}
 {% block content %} 
 {% if form.errors %} 
 {% endif %}
<body class="bg-gradient-warning">
  <div class="container">
    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-12">
            <div class="p-5">
              
              <div style="text-align: center">
                <h1>Creation de Conpte</h1>
                <p>
                  Veuillez utiliser le formulaire suivant pour vous creer un
                  Conpte
                </p>
              </div>

              <form action="" method="post" class="form containe user">
                {% csrf_token %}
                 {% bootstrap_form form %} 
                <button
                  type="submit"
                  class="btn btn-primary btn-user btn-block"
                >
                  Créer un compte
                </button>
                <hr />
                <a href="#" class="btn btn-google btn-user btn-block">
                  <i class="fab fa-google fa-fw"></i> Inscrivez-vous avec Google
                </a>
                <a
                  href="#"
                  class="btn btn-facebook btn-user btn-block"
                >
                  <i class="fab fa-facebook-f fa-fw"></i> Inscrivez-vous avec
                  Facebook
                </a>
              </form>
              <hr />
              <div class="text-center">
                <a class="small" href="{% url 'authapp:password_reset' %}"
                  >Mot de passe oublié?</a
                >
              </div>
              <div class="text-center">
                <a class="small" href="{% url 'authapp:login' %}"
                  >Vous avez déjà un compte? Connexion!</a
                >
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
{% endblock content %}

ecommerce-django-main/templates/authapp/register_done.html
{% extends "base.html" %}
{% block content %}
<h1>Bienvenue {{ new_user.first_name }}!</h1>
<p>Votre compte à été créé avec succès. Maintenant vous pouvez <a href="{% url 'authapp:login' %}">vous connecter</a>.</p>
{% endblock content %}

ecommerce-django-main/templates/authapp/registeruser.html
{% extends "base.html" %} {% load bootstrap4 %} {% block title %}Registration {%endblock title %}
 {% block content %} 
 {% if form.errors %} 
 {% endif %}
<body class="bg-gradient-warning">
  <div class="container">
    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-12">
            <div class="p-5">
              
              <div style="text-align: center">
                <h1>Creation de Conpte</h1>
                <p>
                  Veuillez utiliser le formulaire suivant pour vous creer un
                  Conpte
                </p>
              </div>

              <form action="" method="post" class="form containe user">
                {% csrf_token %}
                 {% bootstrap_form form %} 
                <button
                  type="submit"
                  class="btn btn-primary btn-user btn-block"
                >
                  Créer un compte
                </button>
                <hr />
                <a href="#" class="btn btn-google btn-user btn-block">
                  <i class="fab fa-google fa-fw"></i> Inscrivez-vous avec Google
                </a>
                <a
                  href="#"
                  class="btn btn-facebook btn-user btn-block"
                >
                  <i class="fab fa-facebook-f fa-fw"></i> Inscrivez-vous avec
                  Facebook
                </a>
              </form>
              <hr />
              <div class="text-center">
                <a class="small" href="{% url 'authapp:password_reset' %}"
                  >Mot de passe oublié?</a
                >
              </div>
              <div class="text-center">
                <a class="small" href="{% url 'authapp:login' %}"
                  >Vous avez déjà un compte? Connexion!</a
                >
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
{% endblock content %}